name = "selfcloak"
main = "_worker.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID"

[vars]
# ─── Required Variables ─────────────────────────────
# Generate a random string (e.g., UUID) and paste it here. It's used to sign login sessions.
SECRET = ""
PROJECT_NAME = "default"

# ─── D1 Database ──────────────────
# Storing logs and selfpage files
[[d1_databases]]
binding = "DB"
database_name = "selfcloak_db"
database_id = "test-d1-id"
